### ISSUE TITLE
Ubuntu/Linux support would be great

### ISSUE THREAD

**Issue by mgajda** [g3rv4/OnChrome#6]

**Comment by bjohas** [comment]
Would love Ubuntu/Linux support too!

**Comment by g3rv4** [comment]
I don't use Ubuntu/Linux, so I have very little incentives to add it. I'd welcome PRs adding it, but I'd also need help maintaining it, so I don't think it's reasonable to expect it anytime soon :(

**Comment by bjohas** [comment]
So, that makes sense - no problem. Can I ask you a quick question? 

The behaviour of the plugin is exactly what I'd like: 
- Open all urls matching pattern A in browser 1
- Open all other urls in browser 2.
I get why running a service is necessary.

Is there a slightly simpler version, that could be done without a service? For example, suppose my criterion was:
- Open all urls (in brower 1) which do not match a pattern in the default browser (browser 2).

Would that simplify things?

**Comment by g3rv4** [comment]
not really, the only reason why an extra application is because otherwise you can't open a program from the browser.

the fact that you need to open a different browser based on any criteria means you need this program on the machine.

I wish it wasn't necessary... it adds lots of complexity to this thing.

**Comment by bjohas** [comment]
Yeah, that makes a lot of sense - thank you for the quick answer!
